//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSimpleApp {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form;
		
		protected System.Web.UI.WebControls.Button buttonRed;
		
		protected System.Web.UI.WebControls.Button buttonGreen;
		
		protected System.Web.UI.WebControls.Button buttonBlue;
		
		protected System.Web.UI.WebControls.Button buttonYellow;
	}
}
